version: '2'
services:
  ora-mysql:
    image: mysql:5.7
    container_name: ora-mysql
    environment:
      MYSQL_DATABASE: ora
      # Can change to whatever user you like
      MYSQL_USER: root
      # Can change to whatever password you like
      MYSQL_PASSWORD: root
      # Password for root access
      MYSQL_ROOT_PASSWORD: root
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3308:3306'
    expose:
      # Opens port 3308 on the container
      - '3308'
    restart: always
    # Where the data will be persisted. for db creation
    volumes:
      - ./ora-docker:/docker-entrypoint-initdb.d/